[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
  force = true
